apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstm-deployment
  labels:
    app: backstm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstm
  template:
    metadata:
      labels:
        app: backstm
    spec:
      containers:
        - name: backstm-container
          image: piitan/backstm:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
